package com.timepath.launcher.ui.swing;

import com.timepath.launcher.PackageFile;
import com.timepath.swing.table.ObjectBasedTableModel;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TimePath
 */
@SuppressWarnings("serial")
public class DownloadPanel extends JPanel {

    private static final Logger LOG = Logger.getLogger(DownloadPanel.class.getName());

    ObjectBasedTableModel<PackageFile> tableModel;

    public DownloadPanel() {
        initComponents();
        DefaultTableModel m;
        tableModel = new ObjectBasedTableModel<PackageFile>() {
            @Override
            public String[] columns() {
                return new String[] {"Name", "Progress"};
            }

            @Override
            public Object get(PackageFile o, int columnIndex) {
                switch(columnIndex) {
                    case 0:
                        return o.fileName();
                    case 1:
                        float percent = (o.progress * 100) / o.size;
                        return (percent >= 0 ? percent + "%" : '?');
                    case 2:
                        return o.size;
                    default:
                        return null;
                }
            }
        };
        jTable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
