package com.timepath.launcher.ui.swing;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author TimePath
 */
@SuppressWarnings("serial")
public abstract class RepositoryManager extends JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected JButton     jButton1;
    protected JButton     jButton2;
    protected JPanel      jPanel1;
    protected JScrollPane jScrollPane1;
    protected JTable      jTable1;

    /** Creates new form RepositoryManager */
    protected RepositoryManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jTable1.setModel(new DefaultTableModel(new Object[][] {
        }, new String[] {
                "Repository", "Enabled"
        }
        )
        {
            Class<?>[] types = {
                    Object.class, Boolean.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jButton1.setText("Add from URL");
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton1ActionPerformed(e);
            }
        });
        jButton2.setText("Remove selected");
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton2ActionPerformed(e);
            }
        });
        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel1Layout.createSequentialGroup()
                                                                             .addContainerGap()
                                                                             .addComponent(jButton1)
                                                                             .addPreferredGap(LayoutStyle.ComponentPlacement
                                                                                                      .RELATED)
                                                                             .addComponent(jButton2)
                                                                             .addContainerGap(149, Short.MAX_VALUE))
                                        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                           .addContainerGap()
                                                                           .addGroup(jPanel1Layout.createParallelGroup
                                                                                   (GroupLayout.Alignment.BASELINE)
                                                                                                  .addComponent(jButton1)
                                                                                                  .addComponent(jButton2))
                                                                           .addContainerGap(GroupLayout.DEFAULT_SIZE,
                                                                                            Short.MAX_VALUE))
                                      );
        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING,
                                                  layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jPanel1,
                                                                                      GroupLayout.DEFAULT_SIZE,
                                                                                      GroupLayout.DEFAULT_SIZE,
                                                                                      Short.MAX_VALUE)
                                                                        .addComponent(jScrollPane1,
                                                                                      GroupLayout.PREFERRED_SIZE,
                                                                                      0,
                                                                                      Short.MAX_VALUE))
                                                        .addContainerGap()
                                                 )
                                 );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                      .addGroup(GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                                      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                      .addComponent(jPanel1,
                                                                    GroupLayout.PREFERRED_SIZE,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    GroupLayout.PREFERRED_SIZE)
                                                      .addContainerGap()
                                               )
                               );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    protected abstract void addActionPerformed(ActionEvent evt);

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        removeActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    protected abstract void removeActionPerformed(ActionEvent evt);
    // End of variables declaration//GEN-END:variables
}
